config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  namespace :api do
    # /api/upload_image
    post :upload_image, to: 'utils#upload_image' 
    # /api/users/:id/follow
    resources :users, only: [] do
      member do
        post :follow
      end
    end

    resources :stories, only: [] do
      # /api/stories/:id/clap
      # /api/stories/:id/bookmark
      member do
        post :clap
        post :bookmark
      end
    end
  end

  resources :users, only: [] do
    collection do
      get :pricing # /users/pricing
      get :payment # /users/payment
      post :pay    # /users/pay
    end
  end
 
  resources :stories do
    resources :comments, only: [:create]
  end

  # /@username/文章標題-123
  get '@:username/:story_id', to: 'pages#show', as: 'story_page'

  # /@username/
  get '@:username', to: 'pages#user', as: 'user_page'

  get '/demo', to: 'pages#demo'
  root 'pages#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/story.rb
class Story < ApplicationRecord
  acts_as_paranoid

  extend FriendlyId
  friendly_id :slug_candidate, use: :slugged

  include AASM

  # validations
  validates :title, presence: true

  # relationships
  belongs_to :user
  has_one_attached :cover_image
  has_many :comments
  has_many :bookmarks

  # scopes
  scope :published_stories, -> { published.with_attached_cover_image.order(created_at: :desc).includes(:user) }

  # instance methods
  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize(transliterations: :russian).to_s
  end

  aasm(column: 'status', no_direct_assignment: true) do
    state :draft, initial: true
    state :published

    event :publish do
      transitions from: :draft, to: :published
    end

    event :unpublish do
      transitions from: :published, to: :draft
    end
  end

  private
  def slug_candidate
    [
      :title,
      [:title, SecureRandom.hex[0, 8]]
    ]
  end

end

app/controllers/api/stories_controller.rb
class Api::StoriesController < Api::BaseController
  before_action :find_story

  def clap
    @story.increment!(:clap)
    render json: {status: @story.clap}
  end

  def bookmark
    render json: {status: current_user.bookmark!(@story)}
  end

  private

  def find_story
    @story = Story.friendly.find(params[:id])
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_story, only: [:edit, :update, :destroy]

  def index
    @stories = current_user.stories.order(created_at: :desc)
  end

  def new
    @story = current_user.stories.new
  end

  def create
    @story = current_user.stories.new(story_params)
    @story.publish! if params[:publish]
    
    if @story.save
      if params[:publish]
        redirect_to stories_path, notice: '已成功發佈故事'
      else
        redirect_to edit_story_path(@story), notice: '故事已儲存'
      end
    else
      render :new
    end
  end

  def edit
    
  end

  def update
    if @story.update(story_params)
      case
      when params[:publish]
        @story.publish!
        redirect_to stories_path, notice: '故事已發佈'
      when params[:unpublish]
        @story.unpublish!
        redirect_to stories_path, notice: '故事已下架'
      else
        redirect_to edit_story_path(@story), notice: '故事已儲存'
      end
    else
      render :edit
    end
  end

  def destroy
    @story.destroy
    redirect_to stories_path, notice: '故事已刪除'
  end

  private
  def find_story
    @story = current_user.stories.friendly.find(params[:id])
  end

  def story_params
    params.require(:story).permit(:title, :content, :cover_image)
  end

end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<% if story.errors.any? %>
  <div class="notification is-danger">
    <%= story.errors.full_messages.to_sentence %>
  </div>
<% end %>

<%= form_for(story, html: {class: 'story-editor'}) do |form| %>
  <div class="field">
    <%= image_tag story.cover_image.variant(resize_to_fill: [1000, 800]), class: 'cover-image' if story.cover_image.attached? %>
    <%= form.label :cover_image, '封面圖' %>
    <%= form.file_field :cover_image %>
  </div>

  <div class="field">
    <%= form.label :title, '標題' %>
    <%= form.text_field :title, class: 'input is-primary is-medium' %>
  </div>

  <div class="field">
    <%= form.label :content, '內容' %>
    <%= form.text_area :content, rows: 10, class: 'textarea is-primary is-medium' %>
  </div>

  <div class="field">
    <% if story.published? %>
      <%= form.submit '更新', name: 'save_as_draft', class: 'button is_medium' %>
    <% else %>
      <%= form.submit '儲存草稿', name: 'save_as_draft', class: 'button is_medium' %>
    <% end %>
    <%= form.submit '發佈文章', name: 'publish', class: 'button is_medium is-primary' if story.may_publish? %>
    <%= form.submit '文章下架', name: 'unpublish', class: 'button is_medium is-danger' if story.may_unpublish? %>
  </div>
<% end %>

<%= javascript_pack_tag 'editor' %>

app/views/stories/edit.html.erb
<h1 class="title">編輯故事</h1>

<%= render 'form', story: @story %>

app/views/stories/index.html.erb
<h1 class="title">故事列表</h1>

<% @stories.each do |story| %>
  <div class="content">
    <h2 class="title">
      <%= link_to story.title, edit_story_path(story), class: 'has-text-grey-darker' %>
      <%= content_tag :span, '已發佈', class: 'tag is-primary' if story.published? %>
    </h2>
    <p><%= strip_tags(story.content).truncate(200) %></p>
    <p>
      最後編輯時間:<%= time_ago_in_words(story.updated_at) %>
      <%= link_to '編輯', edit_story_path(story), class: 'button is-text is-small', data:{ turbolinks: "false" } %>
      <%= link_to '刪除', story_path(story), method: 'delete', class: 'button is-danger is-small', data: { confirm: '確認刪除?!'} %>
    </p>
  </div>
  <hr>
<% end %>

app/views/stories/new.html.erb
<h1 class="title">新增故事</h1>

<%= form_for(@story) do |form| %>
  <div class="field">
    <%= form.label :title, '標題' %>
    <%= form.text_field :title, class: 'input is-primary is-medium' %>
  </div>
  <div class="field">
    <%= form.label :content, '內容' %>
    <%= form.text_area :content, rows: 10, class: 'textarea is-primary is-medium' %>
  </div>
  <div class="field">
    <%= form.submit '儲存草稿', class: 'button is_medium' %>
    <%= form.submit '發佈文章', class: 'button is_medium is-primary' %>
  </div>

<% end %>